services:
  db:
    build: ./database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: securecartdb
    ports:
      - "5432:5432" # Expose port for external access (optional, for debugging)
    volumes:
      - db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d securecartdb"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      - ACCESS_TOKEN_SECRET="8d92cfdea655d9c92474798c9952a2230ed707c989d4cf432de12478a7039186e95366d5a2cbd0ce9fee18b7e21e8970c1cc62d30586dee7d95309e824b33d77"
      - REFRESH_TOKEN_SECRET="b256d2d2a1b4a54422c460399e22886606b49b626abe14ea2249da7eab9bfeb15df7d3e2a70b35d223e7bacc2a438844501d68cd9e3198b4b6d6285673719890"

  client:
    build: ./client
    environment:
      - SERVER_NAME=server
      - SERVER_PORT=5000
    ports:
      - "3000:3000"
    depends_on:
      server:
        condition: service_started
        restart: true

volumes:
  db_data:
