version: '3.8'
services:
  db:
    build: ./database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: securecartdb
    ports:
      - "5432:5432" # Expose port for external access (optional, for debugging)
    volumes:
      - db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d securecartdb"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
        restart: true

  client:
    build: ./client
    environment:
      - SERVER_NAME=server
      - SERVER_PORT=5000
    ports:
      - "3000:3000"
    depends_on:
      server:
        condition: service_started
        restart: true

volumes:
  db_data:
