name: CI-CD Pipeline

on:
  push:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilites
        uses: snyk/actions/node@master # Image: snyk/snyk:node-18 ?
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  docker:
    needs: security
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

            # - name: Set up QEMU
            # uses: docker/setup-qemu-action@v3
         
        # Set up Docker Buildx
        
        # Not sure what these are for, not described in build-and-push
        # - name: Checkout
        # uses: actions/checkout@v4
      - name: Set up QEMU # adds support to more platforms (optional)
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # Build and push to DockerHub
      - name: Build and push
        uses: docker/build-push-action@v6
        with: 
          platforms: linux/amd64,linux/arm64 # supported platforms
          push: true
          tags: hedleyb/ccse-cw2:latest # Dockerhub repository
            
            # build:
            # runs-on: ubuntu-latest
            # steps:
            # - uses: actions/checkout@v4
            # - name: Build the Docker Image
            # run: docker compose up --build
